baseURL: "https://billysutomo.com/"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "[~]$ whoami"
    Content: Software Engineer with interests in Server Architecture, Scalable Systems, Android and iOS, and Web Technologies.